### ISSUE TITLE
bug: fastapi 0.66 changed content type inspection logic

### ISSUE THREAD

**Issue by avilior** [sasha-tkachev/fastapi-cloudevents#5]
**Describe the bug**
When I followed the first example, pasting the curl with the binary events I get a response:

`{"detail":[{"loc":["body"],"msg":"value is not a valid dict","type":"type_error.dict"}]}`

When I tried the second curl command, the one with a structured event it worked.

**To Reproduce**

I installed and followed the instructions as per the readme.

I installed using poetry.

**Expected behavior**
I expected to see both structured and binary methods work as specified by the documentation.

**Screenshots**

**System Details (please complete the following information):**

name = "cloudevents" version = "1.6.1"
name = "fastapi" version = "0.85.0"
name = "fastapi-cloudevents" version = "1.0.2"
name = "pydantic" version = "1.10.2"

**Additional context**

**Comment by sasha-tkachev** [comment]
@avilior Thank you for the bug report!

Looking into it right now

**Comment by sasha-tkachev** [comment]
Seems that this is a problem introduced in `fastapi>=0.66.0`. 
Working on a fix. Meanwhile you can downgrade it to `fastapi<0.66.0` as a workaround.

**Comment by sasha-tkachev** [comment]
Released as part of 1.0.3
https://github.com/sasha-tkachev/fastapi-cloudevents/releases/tag/v1.0.3
