### ISSUE TITLE
`type` is not present in real eventarc bodies

### ISSUE THREAD

**Issue by br-follow** [sasha-tkachev/fastapi-cloudevents#6]
**Describe the bug**
When using this package's `CloudEvent` type as a request object, event requests fail due to 422 errors:
```
[ErrorWrapper(exc=ValidationError(model='CloudEvent', errors=[{'loc': ('type',), 'msg': 'field required', 'type': 'value_error.missing'}]), loc=('body',))]
```

The `type` field is not in the request body, but rather, it is present in the `Ce-Type` header.

**To Reproduce**
Run this against real events from eventarc

**System Details (please complete the following information):**
 - Python Version: 3.10.0
 - FastAPI Version: 0.88

**Comment by sasha-tkachev** [comment]
Thank you for the bug report! We will look into it soon

**Comment by sasha-tkachev** [comment]
Sorry but I'm not familiar with eventarc. 
Can you provide here please a sample HTTP or JSON event so I can debug it?

**Comment by sasha-tkachev** [comment]
@br-follow, re-open if it is still relevant
