### ISSUE TITLE
Upgrade to support pydantic v2

### ISSUE THREAD

**Issue by breathe** [sasha-tkachev/fastapi-cloudevents#9]
**Is your feature request related to a problem? Please describe.**

Would like to use `fastapi-cloudevents` when running against the latest `fastapi` which requires pydantic v2

**Describe the solution you'd like**

- Apply steps from the pydantic v2 migration guide -- https://docs.pydantic.dev/latest/migration/
- Make some additional changes to get all tests to pass after migration

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by sasha-tkachev** [comment]
Thank you for your issue and PR submissions!
Will release a new version today probably.

**Comment by sasha-tkachev** [comment]
Merged

**Comment by sasha-tkachev** [comment]
@breathe, sorry for not being able to release a version, yesterday a war broke out in my country so it will probably take me a few more days to release a version.
The terrorists really don't like pydantic v2

**Comment by breathe** [comment]
🫂 @sasha-tkachev I hope you and your loved ones are safe and that all the harm, pain, and fear from these recent events moves rapidly toward their shortest and smallest possible minimums ...

**Comment by sasha-tkachev** [comment]
@breathe , Thank you ❤️
